[redis]
host = ""
port = 6379
db = 2
charset="utf-8"
queue_max_length = 6
queue_ttl = 3600

[open_ai]
key = ["key1","key2"]

[proxy]
host = ""
port = ""

[we_chat_work]
token = ""
encodingAESKey = ""
corpid = ""
corpsecret = ""

[log]
path = "/var/log/chatgpt.log"

[app]
name = "chatGPT"